language: cpp
compiler: gcc
before_install:
  - sudo add-apt-repository ppa:coolwanglu/pdf2htmlex --yes
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libpoppler-dev libfontforge-dev libspiro-dev libcairo-dev libfreetype6-dev
before_script: 
  - cmake -DENABLE_SVG=ON .
script:
  - make
  - make test
  - sudo make install
  - /usr/local/bin/pdf2htmlEX -v
branches:
  only:
    - master
